#!/usr/bin/env python
import sys
import signal
import argparse
from starlette.applications import Starlette
from starlette.routing import Route
import uvicorn

from sendf import SendF


def main():
    parser = argparse.ArgumentParser(prog="sendf")
    parser.add_argument("-o", "--output", type=str, default=None, help="name of the file the user will receive it as")
    parser.add_argument(
        "-e", "--external", action="store_true", default=False, help="whether or not to use an external ip via uPnP"
    )
    parser.add_argument("files", type=str, nargs="+", help="files to send")
    args = vars(parser.parse_args())

    # initialize
    sendf = SendF(args['files'], args['external'], args['output'])
    sendf.initialize()
    print(sendf.link)

    routes = [
        Route('/{uuid}', sendf.call),
    ]

    app = Starlette(debug=False, routes=routes)

    # setup signal handlers
    def signal_handler(signal, frame):
        sendf.finalize()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGQUIT, signal_handler)

    uvicorn.run(app, host='0.0.0.0', port=sendf.port, loop='asyncio')


if __name__ == '__main__':
    main()
