#!/usr/bin/env python
import sys
import signal
import argparse
import cherrypy

from sendf import SendF


def main():
    parser = argparse.ArgumentParser(prog="sendf")
    parser.add_argument("-o", "--output", type=str, default=None, help="name of the file the user will receive it as")
    parser.add_argument(
        "-e", "--external", action="store_true", default=False, help="whether or not to use an external ip via uPnP"
    )
    parser.add_argument("files", type=str, nargs="+", help="files to send")
    args = vars(parser.parse_args())

    # stop cherrypy from printing stuff to the screen
    cherrypy.log.screen = False
    cherrypy.checker.on = False

    # initialize
    sendf = SendF(args['files'], args['external'], args['output'])
    sendf.initialize()
    print(sendf.link)

    # setup signal handlers
    def signal_handler(signal, frame):
        sendf.finalize()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGQUIT, signal_handler)

    # config server and start it up
    cherrypy.config.update({'server.socket_host': '0.0.0.0', 'server.socket_port': sendf.port})
    cherrypy.quickstart(sendf)


if __name__ == '__main__':
    main()
